sync_configs:
  - name: "sync1"
    source_dir: "/path/to/source1"
    target_dirs:
      - "/path/to/target1"
      - "/path/to/target2"
  - name: "sync2"
    source_dir: "/path/to/source2"
    target_dirs:
      - "/path/to/target3"
      - "/path/to/target4"
